module.exports  = {
	AlvaroUribeVel:         'AUV',
  	PalomaValenciaL:      'PV',
  	petrogustavo: 'PG',
  	AndresPastrana_: 'AP',
  	jcvelezuribe: 'JCVU',
  	JuanLozano_R: 'JLR',
  	CarlosHolmesTru: 'CH',
  	mluciaramirez: 'MLR',
  	German_Vargas: 'GVLL',
  	OIZuluaga: 'OIZ',
  	sergio_fajardo:  'SF',
  	JERobledo: 'JER',
  	JuanManSantos: 'JMS',
  	ClaudiaLopez: 'CL',
  	AntanasMockus: 'AM',
  	EnriquePenalosa: 'EP',
  	RafaelPardo: 'RP',
  	piedadcordoba: 'PC',
  	ernestosamperp: 'ESP',
  	IvanCepedaCast: 'ICC',
  	ernestomaciast: 'EMT'
}
